# Generated by Django 3.2.5 on 2022-01-22 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('category', models.CharField(choices=[('Reading', 'Reading'), ('Exercise', 'Exercise'), ('Practicing Music', 'Practicing Music'), ('Writing', 'Writing'), ('Language Learning', 'Language Learning'), ('Savings', 'Savings'), ('Gratitude', 'Gratitude'), ('Productivity', 'Productivity'), ('Relationships', 'Relationships'), ('Healthy Eating', 'Healthy Eating'), ('Parenting', 'Parenting'), ('Meditation', 'Meditation')], max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('imagepath', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_date', models.DateField()),
                ('duration', models.PositiveIntegerField()),
                ('habit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habits.habit')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habits.user')),
            ],
        ),
    ]
