# Generated by Django 3.2.5 on 2022-01-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_auto_20220123_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='habitname',
            field=models.CharField(default='', max_length=254),
        ),
    ]
