# Generated by Django 3.2.5 on 2022-01-23 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0006_auto_20220123_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habit',
            name='end_date',
        ),
        migrations.AlterField(
            model_name='habit',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
