# Generated by Django 3.2.5 on 2022-01-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0008_alter_habit_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='actual_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
