# Generated by Django 3.2.5 on 2022-01-29 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('habits', '0009_alter_tracker_actual_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScorecardHabit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habitname', models.CharField(default='', max_length=254)),
                ('schedule', models.CharField(choices=[('6am-12pm', 'Before Noon'), ('12-6pm', 'Afternoon'), ('6pm-12am', 'Evening')], default='', max_length=254)),
                ('score', models.CharField(choices=[('+', 'Positive'), ('=', 'Neutral'), ('-', 'Negative')], default='', max_length=254)),
                ('user_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
