# Generated by Django 3.2.5 on 2022-01-30 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0010_scorecardhabit'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='color',
            field=models.CharField(choices=[('bg-primary', 'Bg Primary'), ('bg-secondary', 'Bg Secondary'), ('bg-success', 'Bg Success'), ('bg-danger', 'Bg Danger'), ('bg-warning', 'Bg Warning'), ('bg-info', 'Bg Info')], default='', max_length=254),
        ),
    ]
