# Generated by Django 3.2.5 on 2022-02-16 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0011_habit_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='category',
            field=models.CharField(choices=[('Reading', 'Reading'), ('Exercise', 'Exercise'), ('Practicing Music', 'Practicing Music'), ('Writing', 'Writing'), ('Learning', 'Learning'), ('Savings', 'Savings'), ('Gratitude', 'Gratitude'), ('Productivity', 'Productivity'), ('Relationships', 'Relationships'), ('Healthy Eating', 'Healthy Eating'), ('Parenting', 'Parenting'), ('Meditation', 'Meditation')], default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='habit',
            name='repetition',
            field=models.CharField(choices=[('Everyday', 'Everyday'), ('Once a Week', 'Onceaweek')], default='', max_length=254),
        ),
    ]
